### ISSUE TITLE
Difference from reconnecting-websocket

### ISSUE THREAD

**Issue by dandv** [ofirattia/ws-reconnect#2]
How is this module different from @pladaria's [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket), which was published before it?

**Comment by ofirattia** [comment]
@dandv, I think the package you mention more complex. In addition for that, its written in typescript ( in case someone want to fork it ), there are more exposed flags.

Anyway, did you use it? :)

**Comment by ofirattia** [comment]
close since this issue is not active.
